### ISSUE TITLE
List properties of object parameter of a method

### ISSUE THREAD

**Issue by nantas** [fireball-x/firedoc#10]
In JavaScript, it's very common to pass an object as parameter to a function. In API docs, it would be very helpful to be able to generate a parameter list with sub properties of object parameter.

For example, a function with the following parameters:
- command `String` The command to run
- args `Array` List of string arguments
- options `Object`
  - cwd `String` Current working directory of the child process
  - env `Object` Environment key-value pairs
  - stdio `Array|String` Child's stdio configuration. (See below)
  - customFds `Array` Deprecated File descriptors for the child to use for stdio. (See below)

We need a way to comment properties of parameter object and list them under that parameter.

**Comment by yorkie** [comment]
Good, YUIDoc in fact has helped me to achieve this in following syntax:

``` js
/**
 * @method star
 * @param {String} command The command to run
 * @param {Array} args List of string arguments
 * @param {Object} options
 * @param {String} options.cwd
 * @param {Object} options.env
 * @param {Array|String} options.stdio
 * @param {Array} options.customFds
 */
```

The live example is [here](https://github.com/fireball-x/firedoc/blob/fe6ab783a1b680069d4abf9bfd12df101f55360a/tests/input/test/test.js#L180-L193)

**Comment by nantas** [comment]
yeah it works!
