### ISSUE TITLE
@example with @link failed to load file

### ISSUE THREAD

**Issue by nantas** [fireball-x/firedoc#11]
My comment:

``` js
/**
* ...
*@example {@link example1.js }
*/
```

It outputs the example tag value as it is.

I logged the following line:
https://github.com/fireball-x/firedoc/blob/master/lib/docparser.js#L688

It has the correct `examplePath` value, but failed to pass `Y.Files.exists(examplePath)` check.

**Comment by yorkie** [comment]
Hi @nantas could you please copy your test project distribution, and I will take a look at which is in wrong way, Thanks

**Comment by yorkie** [comment]
After reviewed your demo project, we need to specify the relative path should start from the current work directory over the source file, let me show you an example and the common scenario:
- Assume that we have the following project distribution:

```
project
 |- src
 |- docs/api
```
- The best practice to add the `example` folders looks like:

```
project
 |- src
 |- docs/api
 |- examples
```
- Now we can write an example which would link to any file under `./examples`:

``` js
/**
 * description
 * @example {@link examples/filename.js}
 */
```

Hope this temporary doc would help you to address the problem :)
