### ISSUE TITLE
Should remove trailing colon when description is empty for @return tag

### ISSUE THREAD

**Issue by nantas** [fireball-x/firedoc#12]
![image](https://cloud.githubusercontent.com/assets/344547/7646722/2418493a-fafa-11e4-8795-43e49b02f352.png)

Or better add a `type:` text before the  type link, so the above example should render like this:

``` markdown
type: [AnimationNode]
with or without description.
```

**Comment by yorkie** [comment]
Tweaked the UI at latest version :)
