### ISSUE TITLE
@callback tag generate warning in building process, also parameters not displayed

### ISSUE THREAD

**Issue by nantas** [fireball-x/firedoc#13]
My comments:

``` js
        /**
         * @callback loadCallback
         * @param {string} error - null or the error info
         * @param {Asset} data - the loaded asset or null
         */

        /**
         * @method loadAsset
         * @param {string} uuid
         * @param {loadCallback} callback - the callback function once load finished
         * @param {boolean} [readMainCache=true] - If false, the asset and all its depends assets will reload and create new instances from library.
         * @param {boolean} [writeMainCache=true] - If true, the result will cache to AssetLibrary, and MUST be unload by user manually.
         * @param {Asset} [existingAsset] - load to existing asset, this argument is only available in editor
         * 
         */
```

Generates warning: `warn: Missing item type:`.
Also in the generated doc, the callback parameter is not displayed.

In v0.8.27

**Comment by yorkie** [comment]
@nantas could you please copy the complete file, actually it is working for me like the below shot:
![screen shot 2015-05-15 at 5 45 05 pm](https://cloud.githubusercontent.com/assets/1935767/7650552/4358117e-fb2a-11e4-99ac-7d0ff38685a0.png)

**Comment by nantas** [comment]
OK I found where it goes wrong.
The working example of `@callback` is only valid within a `@module` page.
If you put the tag in `@class` scope it will not be rendered.

**Comment by yorkie** [comment]
Still no luck, cant reproduce this description in my side, the below is what I was firedoc-ing:

``` js
/**
 * @class Fire
 */

/**
 * @callback FireCallback
 * @param {String} name - the name of your fire
 * @param {String} view - the view page to render
 */

/**
 * @method test_the_callback_tag_in_class_scope
 * @param {String} funcparam1
 * @param {FireCallback} cb
 */
```

This is working at my classes view, can you just copy the above comments and firedoc it, then check what do you get? Thank you @nantas

**Comment by nantas** [comment]
I can confirm your example is working on my machine. I'll send you a complete file that can reproduce this issue.

**Comment by yorkie** [comment]
Okay, feel free to send it at anytime :)
