### ISSUE TITLE
separate default theme to standalone node pacakge 

### ISSUE THREAD

**Issue by nantas** [fireball-x/firedoc#17]
We would like to make some changes to default theme or make a new theme to work with firedoc.
I think it's better to make default theme a dependency of firedoc. So theme changes don't result in firedoc version bump.

new repo is created: https://github.com/fireball-x/firedoc-theme-default

**Comment by yorkie** [comment]
Copy, I will find an easy way to load remote themes.

**Comment by yorkie** [comment]
Closing this, because we have the remote way to install a theme for firedoc at https://github.com/fireball-x/firedoc#themes, now I will move to `notab` theme :)
