### ISSUE TITLE
Add process tag for Electron

### ISSUE THREAD

**Issue by nantas** [fireball-x/firedoc#22]
In Electron, there are [two processes](https://github.com/atom/electron/blob/master/docs/tutorial/quick-start.md). Some API only works in one process. 

In Fireball we also have these two processes:
- core-level process (electron's main process)
- page-level process (electron's renderer process)

In order for reader to understand which API can work in which process, we need to add a tag representing the process it runs in. Such as `@process core` `@process page`.

It will add a label to the right of the class item name.

**Comment by yorkie** [comment]
There is one question and one proposal:
1. question: what's the parent tag of the new tag? I mean now it's for class only? or we should support it for `module`, `enum` and even members and methods of them?
2. proposal: how about changing the `process` to `worker`, the latter is more close to the ECMAScript's definition, it might be used for browsers.

**Comment by jwu** [comment]
1. we should support it for class, module and any other members in it.
2. I think they are different, the process only introduced from Electron.

~~BTW: we still need a syntax like this: `@process core, page`, since some modules are shared in both process.~~

**Comment by yorkie** [comment]
Copy that :)

**Comment by jwu** [comment]
There's an example for this issue, I'm going to move https://github.com/fireball-x/editor-framework 's document from jsdoc to firedoc, 

Some of them such as Editor.Panel, defined in both core and page process, with different comments: 
- https://github.com/fireball-x/editor-framework/blob/master/core/editor-panel.js
- https://github.com/fireball-x/editor-framework/blob/master/page/editor-panel.js

so I should mark them with different tag, a.k.a `@process core` and `@process page`.

And some others such as Editor.IpcListener live in both process:
- https://github.com/fireball-x/editor-framework/blob/master/share/ipc-init.js

(While I typing this, I found the module live in both process don't need any tag to hint it)

**Comment by yorkie** [comment]
Oh what's the default behavior when no definition of `@process`? for both or for none?

**Comment by jwu** [comment]
em.... that is a good question. What's your opinion @nantas ? If default behaviour is for both, we should mark every method with `@process` except those in `share/` folder. 

I guess none will be a good choice? What do you think ?

**Comment by yorkie** [comment]
By the way, I found the editor-framework is using a `namespace` tag which is not supported by firedoc, should we introduce it as well, or just by implementing with sub-module?

**Comment by jwu** [comment]
oh, I haven't change the comment to firedoc. Right now I have no idea, I prefer use the firedoc's way for them, and it should be sub-module.

**Comment by yorkie** [comment]
Got it, thanks for sharing :)

**Comment by nantas** [comment]
without a `@process` tag means it works in both processes.

**Comment by yorkie** [comment]
marked

**Comment by nantas** [comment]
When migrating editor-framework's doc from JSDoc to FireDoc, some thoughts from reviewing source code:
- Some method are shared in both core and page level `Editor` module, such as `Editor.require`, `Editor.log`, do they need different description or signature? If they can be the same, should we add a `@main` tag at one of the definition to indicate where should we get the description?
- To simplify our commenting process, we should be able to set a `@process core` tag to a module or class definition. This indicate **EVERYTHING** under this module or class is limited to core process only, unless there are explicit tagging for its child item.

example:

``` js
/**
* @module Editor.Panel
* @process core
*/
```

Means everything under Editor.Panel is core process only.

``` js
// in Editor module
/**
 * Log the normal message and show on the console.
 * The method will send ipc message `console:log` to core.
 * @method log
 * @main
 * @param {...*} [arg] - whatever arguments the message needs
 */
```

Means there may be other `Editor.log` method definition somewhere, but please use this definition for generating doc for this method. Because there're no `@process` tag, so this method will be displayed with core and page both available.

``` js
/**
 * Editor is a module contains app-wide core editor functionality. You can access properties or methods of Editor module anytime, anywhere in Fireball
 * @module Editor
 * @main
 * @process core
 */
```

By adding a `@process core` to the `Editor` module definition, we would by default add `core` only tag to all members/methods under `Editor` module, unless it's explicitly declared otherwise:

``` js
/**
 * Log the normal message and show on the console.
 * The method will send ipc message `console:log` to core.
 * @method sendToCore
 * @process page
 * @param {...*} [arg] - whatever arguments the message needs
 */
```

thoughts? @jwu @yorkie

**Comment by yorkie** [comment]
I'd rather than using the only one description for different runtimes(processes), because we have to care about the i18n, if we adds too much conditions on description, the experiences seems to go worse I guess, and even we call it `description`, so we completely tell the readers like:

```
/**
 * This method are shared at core and page, in different processes, they also have different behaviors:
 * 1. In core process, balalabalala
 * 2. In page process, balalalalalbabalala
 * @method log
 * @process
 */
```

Oh wait, is there the possibility for one function would have different returned value or parameters definition in different processes? Or we should specify this in different methods?

As for the new tag `@process`, I have figure out how to implement, and as well I also though out that we should make the module's member or submodule should be consistent with their parent, on which we used the tag `@process`. However, **Do we need a page to describe the process core and page**? or we can directly redirect to the extern link, like electron docs?

**Comment by jwu** [comment]
It is possible an API have different parameters or return value in core and page process, but this is a **BAD** design, and we should 100% avoid these kind of API. I believe the API with the same name under the same module should have the same objective (implementation can be different, but they should act the same behaviour).

I agree with @yorkie and I suggest we write the description in one place if the API exists in both processes, perhaps the core-process. And we should add additional text to describe the difference of them.

**Comment by yorkie** [comment]
v1.8.x has implemented the part of task in firedoc itself, which adds the process in AST correctly, now moving the rest work to downstream repo: https://github.com/fireball-x/firedoc-theme-notab/issues/6

**Comment by yorkie** [comment]
Oh @jwu @nantas do we need somewhere to document what are these processes? just like describe what's `core` and what's the `page`? Or we just provide a url link to Electron wiki?

**Comment by jwu** [comment]
I think we should simply introduce them, and put a link to Electron's wiki. 

@nantas A user with only web-programming background may be confused by Electron's document about main and renderer process, but if you compare it with server and client architecture, they will get it immediately.

**Comment by yorkie** [comment]
> I think we should simply introduce them

So as @jwu described, we still need a page to document the processes by ourselves, and we can put the link to the description as markdown link? Am I right?

**Comment by nantas** [comment]
I wrote a little bit explanation here: http://docs.fireball-x.com/editor/ipc-channel/#Core_and_Page_Process

You can link your process tag to this page as for now. @yorkie

**Comment by yorkie** [comment]
noted and reopening...

**Comment by nantas** [comment]
sorry I missed this notification yesterday...

**Comment by yorkie** [comment]
never mind, i have not yet started this one :)

**Comment by yorkie** [comment]
Done
