### ISSUE TITLE
use firedoc-api

### ISSUE THREAD

**Issue by yorkie** [fireball-x/firedoc#37]
https://github.com/firedoc/firedoc-api

**Comment by yorkie** [comment]
firedoc-api would be deprecated and will use Github releases to replace the node-git.

**Comment by yorkie** [comment]
@jwu I have removed the heavy dependence `nodegit` when the version >= `0.10.0`.

**Comment by jwu** [comment]
OK, I will update the package.json of editor-framework and fireball for this.

**Comment by yorkie** [comment]
And now I guess we are able to remove the firedoc-api(DEPRECATED) as well, let me make a double check.

**Comment by yorkie** [comment]
@jwu I have released a new version `v0.3.0` of code-editor that uses the module `firedoc` to replace `firedoc-api`. Therefore, before updating the version of firedoc, please do the following checklist:
- `firedoc` >= `0.10.0` in `dependencies` or `devDependencies`
- `builtin/code-editor` >= `0.3.0`
- remove `firedoc-api`

In next week, I'm planing to include the `firedoc-intelisense`'s source into `code-editor` either.
