### ISSUE TITLE
My class description output escaped html tag

### ISSUE THREAD

**Issue by nantas** [fireball-x/firedoc#39]
The problematic page: http://docs.fireball-x.com/api/classes/NodeWrapper.html

Source: https://github.com/fireball-x/engine-framework/blob/master/src/runtime/wrappers/node.js#L19-L59

Other classes are working ok (for example http://docs.fireball-x.com/api/classes/EngineWrapper.html), not sure what's wrong with this.

**Comment by yorkie** [comment]
I do suspect this might be caused by the complex en/zh description which I didn't consider about before, I will add this case to our test soon later then it would work :)

**Comment by yorkie** [comment]
@nantas I have fixed this at `v1.9.1`, and also did fix the sort issue of sidebar at the latest version `v1.9.2`. 

BTW, I found there still is a typo on the given [comments](https://github.com/fireball-x/engine-framework/blob/master/src/runtime/wrappers/node.js#L19-L59): `!#zh:` should be corrected as `!#zh`(remove the colons)
