### ISSUE TITLE
Can't find main module description correctly in Fireball setup

### ISSUE THREAD

**Issue by nantas** [fireball-x/firedoc#7]
In Fireball we inserted `@module` for each source file when generating api doc.
The main Fire module definition is in `src/core/src/__intro.js` like this:

``` js
    /**
     * description
     * @module Fire
     * @main Fire
     */
```

But in generated Fire module page, it shows the Fire module is defined in `utils/api/engine/transform.js:6`.

**Comment by nantas** [comment]
Fire main module is marked correctly, but Editor is still wrongly defined in `ipc-init.js`

**Comment by yorkie** [comment]
This is because in fireball-x/editor, it only does export the file `ipc-init.js` at [this line](https://github.com/fireball-x/editor/blob/dev/gulpfile.js#L68), so the `yuidoc` would not handle with the main file `editor-init.js`.

**Comment by nantas** [comment]
@jareguo should we export `editor-init.js` as well?

**Comment by jareguo** [comment]
Sure
